info:
  profile: default
  from: git1
  password: '{cipher}AQBvKr7aoJSAY0kJ3rpWmuY17As/cUzDKw9Oaqg3nliyCa4N7Mzm/UQNmVtkuopgJ88ZsUzby+CrCcbVVXjrT5yXW/hYU4S+ce6o1HJD3cWes1Y24muCo1iXTJbNW9g9ZOUU5oD7bYMlk4ThHRMW8Cqn/doiwLOS3ov0EXJaN8AeW28oYQwYn6OQJyEf6K1/y7QRNliQWsqmbOTktKWjkxMGw3pAmLfyxje39ljo2jvZtQrVNXFMtmOrubzZO84ZRcznTw7DTdj8e3lKaU8vqdhfHs9kBHrEh7CauRB3QlqEc3VeSGaArLZ4vpmrflUbQdjxjnmcvpWiw9AHbzMSzE/xe3Jpqc7F4l2i3RVPWE1xCfJn/2BTMY36m637CLsTNF8='
test: bbb