info:
  profile: default
  from: git1
  password: '{cipher}AQCDm29eFnOHK63DX+TyNUkk9YT+Uc6bzA85pr464iyh9sFpDL84HpI5SFoa/+kXrBhp/nXeqWYC3z3EBlaxLIYgkchQx+ctixqkjXps8hCPnI+CE/SCyR4rqTF1O+/eYUdK2yXiA6uVkLGEGD7Qga0kBqm/KQftXZLs9NgdDgxO+XCRQ3Js4oK43VWct+XEP/11Urds1LY+VRlBDrsA9wL2/xtNhT/9x3pLPbr6Rr/m34M2mPSiNBq7Lp00C+acDe1utnegOwDSxHmv7kYT+KvKJdVNPMypNh/kt8EMIY5ZCXpzBQoqWQhpa7tfQC2De4BTp6umzX8nkEro7L1BJ1vEpvWQPN6VpdSBcIPPBWBvX2UDxafdAdnRKHTqDQyFj/0='
test: bbb