server:
  port: 2005
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      #是否启用分段上传支持，默认true
      enabled: true
      #最大单个文件大小，值可以使用后缀“MB”或者“KB”分别标识兆字节或者千字节，默认1MB
      max-file-size: 20MB
      #最大请求大小，值可以使用后缀“MB”或者“KB”分别标识兆字节或者千字节，默认10MB
      max-request-size: 100MB
      #文件写入磁盘的阈值，当上传文件到1M时开始写入磁盘，值可以使用“MB”或者“KB”分别标识兆字节或者千字节
      file-size-threshold: 1MB
      #上传文件的临时位置
      location: /
      
management:
  endpoints:
    web:
      exposure:
        include: '*'