server:
  port: 2007
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:  
  mail:
    default-encoding: UTF-8
    host: smtpcom.263xmail.com
    port: 25
    username: qinjili@idengyun.com
    password: '{cipher}AQAEEeCxgZnObXWsfpMHLmpATypYfaQZ+JU40kF43387W+cl9eTF0G60re/D4ctA6SNLK8PQ4/YW7H0BXBMTRF/zzq3LJM5LZfk9FxfBy1LGdCYrFale36ELcJDePP06zKV3H8VXYvSvsn0svDthVL9SXMnmp7voB3jzz9PI3ONu1hWdFqSWjoy8KifnSTCGZEM5v9ggAy5jBamteKKqcrm5rIPh1DFfaqeaL286dWk7VQBdQOVuT5JbxBwUaH17xjhImvcXsRiuxbjaOMCJO52OKdTfGlkeMMd8RfnY8Nn+X8gtLE1tRNyCTQmrMM4gBqtfXNYrAEFiE8vlE6lYRmiNhkRh5EiPnyh6xsZO2o6u3wIMRqAC+YPV35aoKcC8BA8='
    properties:
      mail:
        stmp:
          auth: true
          timeout: 30000
  datasource:
    name: mydb
    #使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #配置基本属性
      url: jdbc:mysql://192.168.131.130:3306/edm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
      username: root
      password: '{cipher}AQBRbrXO2xZNHwc1uzuvxk+6M27L/QwQX/kAGWs8R0e5IgGDxlpxAF1ZNWzD9AwnOq1n+dnxYMK3vk4xJn39eRJlUJ1WiQqZhXFvG5M0S5KvWSm7xdgPhLyIqJaXrl6+gI6w5SWiFgMlp/MrlWsPAwVU3lC0LqUExT7T6wgCJGYDkax7up2Gr/+twvAjLu1v67b65RC33lvXTrWJ9cZv68cDfWNY6wZLpAc1VP7Wj4dndIQzHW1TKtmWr2GoauzeT/uiObqOTAjuedFdT0lyTnlz7dMh7rVNQF1/ZMurOeSh83GMlh0RS8HNDIRuv9ytI64F8W7kNt17aKjzS0lBV4p3LYUxVlQ3OrazXdI5WsfBhObvrNwqEOA3fgZuGiw8ULg='
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
mybatis:
  # 映射文件所在路径
  mapper-locations: classpath:mapper/IMailSendMapper.xml
  # pojo类所在包路径
  type-aliases-package: com.dengyun.saasedm.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql