spring:
  mail:
    default-encoding: UTF-8
    host: smtpcom.263xmail.com
    port: 25
    username: qinjili@idengyun.com
    password: qwer1234
    properties:
      mail:
        stmp:
          auth: true
          timeout: 30000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
  instance:
    hostname: localhost